#!/bin/bash

vimprofile=~/.vimrc
gitdir=~/git
vimkitdir="$gitdir/vim-kit"
vimkitfile="$gitdir/vim-kit/vimrc.vim"
plugindir="$gitdir/vim-plugins"

failure() {
	for ((i=1;i<=$#;i++))
	do
		echo "${!i}" 1>&2
	done

	echo $'\nFailed!'

	exit 1
}

run_cmd() {
	echo "$1"

	if ! eval "$1"
	then
		failure
	fi
}

get_current_branch_name() {
	local name=$(git branch --no-color | awk '{if (NF==2 && $1=="*") print $2}')

	if [ -z "$name" ]
	then
		failure "Curent branch name is unknown. Check 'git branch --no-color'."
	fi

	echo -n "$name"
}

# Check if ctags has been installed or not
if ! which ctags > /dev/null 2>&1
then
	failure 'Please run "sudo yum install ctags" first.'
fi

# update vim-kit first!
run_cmd "cd '$vimkitdir'"
if [ `get_current_branch_name` == "master" -a `git status -s | wc -l` -eq 0 ]
then
	run_cmd "git pull"
fi

if [ ! -f "$vimkitfile" ]
then
	failure "Could not find file '$vimkitfile'."
fi

# Get a list of VIM plugins
v1=`cat "$vimkitfile" | sed -nr '/^[ \t]*Plugin[ \t]+.*/p' | awk '{print $2}' | awk 'BEGIN{FS=","} {print $1}'`
v1="${v1//\// }"
v1="${v1//\'/ }"
plugins=($v1)

if ((${#plugins[@]} == 0 || ${#plugins[@]} % 2 != 0))
then
	failure "The plugin list in file '$vimkitfile' is incorrect."
fi

# Create folder ~/git/vim-plugins
if [ ! -d "$plugindir" ]
then
	run_cmd "mkdir -p '$plugindir'"
fi

for ((i=0;i<${#plugins[@]};i+=2))
do
	subdir="$plugindir/${plugins[i+1]}"

	if [ -d "$subdir" ]
	then
		run_cmd "cd '$subdir'"
		run_cmd "git pull"
	else
		run_cmd "cd '$plugindir'"
		run_cmd "git clone 'https://github.com/${plugins[i]}/${plugins[i+1]}.git'"
	fi
done

# ln -s ~/git/vim-kit/vimrc.vim ~/.vimrc
if [ -L "$vimprofile" -o -f "$vimprofile" ]
then
	if [ ! "$vimkitfile" -ef "$vimprofile" ]
	then
		run_cmd "mv -f '$vimprofile' '$vimprofile.old'"
		run_cmd "ln -s '$vimkitfile' '$vimprofile'"
	fi
else
	run_cmd "ln -s '$vimkitfile' '$vimprofile'"
fi

# run helptags for each plugin.
for ((i=0;i<${#plugins[@]};i+=2))
do
	docdir="$plugindir/${plugins[i+1]}/doc"

	if [ -d "$docdir" ]
	then
		run_cmd "vim --noplugin -n -c 'helptags $docdir | q'"
	fi
done

# Build gocode and move gocode binary to $HOME/bin
if which go > /dev/null 2>&1
then
	if [ -z "$GOROOT" ]
	then
		failure 'Environment variable GOROOT is not set.'
	fi

	gocodedir="$plugindir/gocode"
	if [ -d "$gocodedir" ]
	then
		run_cmd "cd '$gocodedir'"
		run_cmd "go build"

		if [ ! -f "$gocodedir/gocode" ]
		then
			failure "gocode could NOT be compiled."
		fi

		if [ ! -d ~/bin ]
		then
			mkdir ~/bin
		fi

		run_cmd "mv -f '$gocodedir/gocode' ~/bin/."

		# Check gocode is in PATH
		if ! which gocode > /dev/null 2>&1
		then
			failure 'Please add "export PATH=$PATH:~/bin" to ~/.bash_profile, re-log into system and try again.'
		fi
	fi
fi

# Success
echo -e "\nDone! All VIM plugins have been installed/updated to latest!\n"

