#!/bin/bash

gitdir=~/git
vimkitdir="$gitdir/vim-kit"
plugindir="$gitdir/vim-plugins"

failure() {
	for ((i=1;i<=$#;i++))
	do
		echo "${!i}" 1>&2
	done

	exit 1
}

run_cmd() {
	echo "$1"

	if ! eval "$1"
	then
		failure $'\nFailed!'
	fi
}

get_current_branch_name() {
	local name=$(git branch --no-color | awk '{if (NF==2 && $1=="*") print $2}')

	if [ -z "$name" ]
	then
		failure "Curent branch name is unknown. Check 'git branch --no-color'."
	fi

	echo -n "$name"
}

# update vim-kit first!
run_cmd "cd '$vimkitdir'"
if [ `get_current_branch_name` == "master" -a `git status -s | wc -l` -eq 0 ]
then
	run_cmd "git pull"
fi

if [ ! -f "$vimkitdir/vimrc" ]
then
	failure "Could not find file '$vimkitdir/vimrc'."
fi

# Get a list of VIM plugins
v1=`cat "$vimkitdir/vimrc" | sed -nr '/^[ \t]*Plugin[ \t]+'.*\\\\/.*'/p' | awk '{print $2}'`
v1="${v1//\// }"
v1="${v1//\'/ }"
plugins=($v1)

if ((${#plugins[@]} == 0 || ${#plugins[@]} % 2 != 0))
then
	failure "The plugin list in file '$vimkitdir/vimrc' is incorrect."
fi

# Create folder ~/git/vim-plugins
if [ ! -d "$plugindir" ]
then
	run_cmd "mkdir -p '$plugindir'"
fi

for ((i=0;i<${#plugins[@]};i+=2))
do
	subdir="$plugindir/${plugins[i+1]}"

	if [ -d "$subdir" ]
	then
		run_cmd "cd '$subdir'"
		run_cmd "git pull"
	else
		run_cmd "cd '$plugindir'"
		run_cmd "git clone 'https://github.com/${plugins[i]}/${plugins[i+1]}.git'"
	fi
done

# ln -s ~/git/vim-kit/vimrc ~/.vimrc
if [ -L ~/.vimrc -o -f ~/.vimrc ]
then
	if [ ! "$vimkitdir/vimrc" -ef ~/.vimrc ]
	then
		run_cmd "mv -f ~/.vimrc ~/.vimrc.old"
		run_cmd "ln -s '$vimkitdir/vimrc' ~/.vimrc"
	fi
else
	run_cmd "ln -s '$vimkitdir/vimrc' ~/.vimrc"
fi

# Success
echo -e "\nDone! All VIM plugins have been installed/updated to latest!\n"

